### ISSUE TITLE
Index of chapters becomes disordered on update

### ISSUE THREAD

**Issue by kipukun** [aplanas/kmanga#1] opened 2016-12-28 03:28 UTC
When updating the list of chapters from Batoto, new chapters are put in-between already existing chapters, as such:

![ss 2016-12-27 at 10 24 08](https://cloud.githubusercontent.com/assets/6733106/21513144/5516befc-cc83-11e6-83b9-6dd984e1649d.png)

Notice how 82 and 83 are in the wrong order. Before I updated it, 81 was the latest chapter from Batoto.

Unsubscribing and resubscribing does not resolve the issue. This manga is being published as of filing this bug.

**Comment by kipukun** [comment] 2016-12-28 03:35
Update: It seems as though the MangaFox version is in the correct order. I will check how it reorders when it updates tomorrow (12/28/2016) @ around 12 PM

**Comment by aplanas** [comment] 2016-12-28 10:24
Right. The problem is in how the spider works. To avoid multiple access to batoto and to some other sites I only read in the front page the new chapters. With this information I do not know the correct position of the inside the full list, but I can guess it based on the chapter number.

This is not enough, and the new spiders like unionmangas, submangaorg use a different approach that I need to port to batoto.

All Sundays the spider goes to all manga and converge the order of the chapters.

**Comment by aplanas** [comment] 2017-02-23 19:43
This should be fixed with this:

https://github.com/aplanas/kmanga/commit/2f6c930e342af77d23f5d974b28d303fd707101b
https://github.com/aplanas/kmanga/commit/04ebf7d401a833fa5310af0c3d8c23f765617f4b
https://github.com/aplanas/kmanga/commit/e68289230b614b09482451f13362b4b5267cadbc
https://github.com/aplanas/kmanga/commit/30030adb444802e9b30c88a9c9a4d74d3f0d2d7a
https://github.com/aplanas/kmanga/commit/fbd9ef49870e7b9df6edf37dfbe671ac526507e6
https://github.com/aplanas/kmanga/commit/f294f3c4dc07c1bcad066e32c6d269269aa62261
https://github.com/aplanas/kmanga/commit/6cd71b1e21b48b9927d408c33b985707b3275713

**Closed by aplanas** 2017-02-23 19:43 UTC
